
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'config.ru'
    - 'lib/testing/recomendation_um.rb'
Metrics/AbcSize:      # Отключение ABC-проверок
  Enabled: false
Metrics/LineLength:   # Длина строк 120
  Max: 120
Metrics/MethodLength: # Количество строк кода 15
  Max: 15
Style/NegatedIf:      # Не форсировать unless
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Metrics/ParameterLists:
  Max: 6